---
- name: Create a symbolic link Arm
  file:
    src: /var/www/html/cumulus-linux-{{ cumulus_current_firmware }}-bcm-armel.bin
    dest: /var/www/html/onie-installer-arm
    state: link
  tags: 
    - firmware
    - content

- name: Create a symbolic link ADM
  file:
    src: /var/www/html/cumulus-linux-{{ cumulus_current_firmware }}-bcm-amd64.bin
    dest: /var/www/html/onie-installer-x86_64
    state: link
  tags: 
    - firmware
    - content
