---
- name: create users
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups:
      - adm
  with_items: "{{ admin_users }}"

- name: set ssh_dirs
  file:
    state: directory
    name: /home/{{item.username}}/.ssh
    owner: "{{item.username}}"
    group: adm
    mode: 0700
  with_items: "{{ admin_users }}"

- name: set public keys
  copy:
    content: "{{ item.key_format | default ('ssh-rsa') }} {{ item.public_key }} {{ item.username }}"
    dest: /home/{{item.username}}/.ssh/authorized_keys
    owner: "{{ item.username }}"
    group: adm
    mode: 0600
  with_items: "{{ admin_users }}"
