---
- name: Allow 'adm' to passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%adm'
    line: '%adm ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create privilege group
  group:
    name: "{{ item.privilege_group | default( item.username ) }}"
    state: present
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: users

- name: Create user
  user:
    name: "{{ item.username }}"
    group: "{{ item.privilege_group | default( item.username ) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: users

- name: Set ssh_dir
  file:
    state: directory
    name: /home/{{ item.username }}/.ssh
    owner: "{{ item.username }}"
    group: "{{ item.privilege_group | default( item.username ) }}"
    mode: 0700
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: users

- name: Set public key
  copy:
    content: "{{ item.key_format | default ('ssh-rsa') }} {{ item.public_key }} {{ item.username }}"
    dest: /home/{{ item.username }}/.ssh/authorized_keys
    owner: "{{ item.username }}"
    group: "{{ item.privilege_group | default( item.username ) }}"

    mode: 0600
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.username }}"
  tags: users
