---
- name: reload networking
  command: "ifreload -a"

- name: restart dhcp
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
