---
- name: reload networking
  command: "ifreload -a"

- name: restart dhcp
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted
    
- name: reload motd 
  shell: base64 -d /etc/motd.base64 > /etc/motd

 
